# Generated by Django 3.1.4 on 2020-12-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='name')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
    ]
